### PR TITLE
Provide meta information about the reports

### PR DESCRIPTION
**Pull request by frances-h**
CU-860q8k97g

### CODE REVIEW

**Review by amontanez24 — APPROVED** [review]
LGTM!

**Review by amontanez24 — APPROVED** [review]
LGTM! Maybe we can move the issue from private over to this repo and tag it

**Comment by npatki** [comment]
Unfortunately, I think you can only transfer issues within a single organization (like `sdv-dev`)n

**Review by pvk-developer — APPROVED** [review]
LGTM :shipit: !

**Pull request merged**
